-- Canonical skills (~80)
INSERT INTO skills (canonical, aliases, approved) VALUES
  ('React', ARRAY['ReactJS','React.js'], true),
  ('Vue', ARRAY['VueJS','Vue.js','Vue3'], true),
  ('Angular', '{}', true),
  ('Svelte', '{}', true),
  ('Next.js', ARRAY['NextJS','Next'], true),
  ('Nuxt', '{}', true),
  ('Remix', '{}', true),
  ('TypeScript', ARRAY['TS'], true),
  ('JavaScript', ARRAY['JS','ES6'], true),
  ('HTML', '{}', true),
  ('CSS', '{}', true),
  ('Tailwind', ARRAY['Tailwind CSS','TailwindCSS'], true),
  ('SCSS', ARRAY['Sass'], true),
  ('Node.js', ARRAY['Node','NodeJS'], true),
  ('Express', '{}', true),
  ('NestJS', '{}', true),
  ('Go', ARRAY['Golang'], true),
  ('Python', '{}', true),
  ('Django', '{}', true),
  ('FastAPI', '{}', true),
  ('Flask', '{}', true),
  ('Java', '{}', true),
  ('Spring', ARRAY['Spring Boot'], true),
  ('Kotlin', '{}', true),
  ('Swift', '{}', true),
  ('Objective-C', '{}', true),
  ('C#', ARRAY['CSharp'], true),
  ('.NET', ARRAY['dotnet'], true),
  ('PHP', '{}', true),
  ('Laravel', '{}', true),
  ('Ruby', '{}', true),
  ('Rails', ARRAY['Ruby on Rails'], true),
  ('Rust', '{}', true),
  ('C++', ARRAY['Cpp'], true),
  ('C', '{}', true),
  ('Scala', '{}', true),
  ('Elixir', '{}', true),
  ('PostgreSQL', ARRAY['Postgres','pg'], true),
  ('MySQL', '{}', true),
  ('MongoDB', '{}', true),
  ('Redis', '{}', true),
  ('Elasticsearch', ARRAY['ES'], true),
  ('SQL', '{}', true),
  ('GraphQL', '{}', true),
  ('REST', ARRAY['RESTful'], true),
  ('gRPC', '{}', true),
  ('Docker', '{}', true),
  ('Kubernetes', ARRAY['k8s'], true),
  ('AWS', '{}', true),
  ('GCP', ARRAY['Google Cloud'], true),
  ('Azure', '{}', true),
  ('Terraform', '{}', true),
  ('Ansible', '{}', true),
  ('CI/CD', '{}', true),
  ('Git', '{}', true),
  ('Linux', '{}', true),
  ('Figma', '{}', true),
  ('Sketch', '{}', true),
  ('Adobe XD', ARRAY['XD'], true),
  ('Photoshop', ARRAY['PS'], true),
  ('Illustrator', ARRAY['AI'], true),
  ('Premiere', '{}', true),
  ('After Effects', ARRAY['AE'], true),
  ('Excel', '{}', true),
  ('Word', '{}', true),
  ('PowerPoint', ARRAY['PPT'], true),
  ('Notion', '{}', true),
  ('Slack', '{}', true),
  ('Trello', '{}', true),
  ('Jira', '{}', true),
  ('SEO', '{}', true),
  ('Google Analytics', ARRAY['GA','GA4'], true),
  ('Facebook Ads', ARRAY['Meta Ads'], true),
  ('Google Ads', '{}', true),
  ('TensorFlow', '{}', true),
  ('PyTorch', '{}', true),
  ('Pandas', '{}', true),
  ('NumPy', '{}', true),
  ('LLM', '{}', true),
  ('Prompt Engineering', '{}', true),
  ('Unity', '{}', true),
  ('Unreal', ARRAY['Unreal Engine'], true);

-- Canonical roles (~40)
INSERT INTO roles (canonical, aliases, approved) VALUES
  ('前端工程師', ARRAY['Frontend Engineer','Front-end Developer'], true),
  ('後端工程師', ARRAY['Backend Engineer','Back-end Developer'], true),
  ('全端工程師', ARRAY['Fullstack Engineer','Full-stack Developer'], true),
  ('行動工程師', ARRAY['Mobile Engineer','iOS Engineer','Android Engineer'], true),
  ('資料工程師', ARRAY['Data Engineer'], true),
  ('資料科學家', ARRAY['Data Scientist'], true),
  ('機器學習工程師', ARRAY['ML Engineer','Machine Learning Engineer'], true),
  ('AI 工程師', ARRAY['AI Engineer'], true),
  ('DevOps 工程師', ARRAY['DevOps Engineer','SRE'], true),
  ('系統工程師', ARRAY['Systems Engineer'], true),
  ('資安工程師', ARRAY['Security Engineer'], true),
  ('QA 工程師', ARRAY['QA Engineer','測試工程師','Test Engineer'], true),
  ('UI 設計師', ARRAY['UI Designer'], true),
  ('UX 設計師', ARRAY['UX Designer'], true),
  ('UI/UX 設計師', ARRAY['UI/UX Designer'], true),
  ('平面設計師', ARRAY['Graphic Designer'], true),
  ('產品經理', ARRAY['PM','Product Manager'], true),
  ('專案經理', ARRAY['Project Manager','PJM'], true),
  ('工程經理', ARRAY['Engineering Manager','EM'], true),
  ('技術主管', ARRAY['Tech Lead'], true),
  ('行政助理', ARRAY['Administrative Assistant'], true),
  ('業務', ARRAY['Sales','業務代表'], true),
  ('客服', ARRAY['Customer Service','Customer Support'], true),
  ('行銷企劃', ARRAY['Marketing Specialist','Marketing'], true),
  ('社群小編', ARRAY['Social Media Manager','小編'], true),
  ('內容編輯', ARRAY['Content Editor'], true),
  ('文案', ARRAY['Copywriter'], true),
  ('攝影師', ARRAY['Photographer'], true),
  ('剪輯師', ARRAY['Video Editor'], true),
  ('外送員', ARRAY['Delivery'], true),
  ('司機', ARRAY['Driver'], true),
  ('店員', ARRAY['Clerk','工讀生'], true),
  ('廚師', ARRAY['Chef','Cook'], true),
  ('美髮設計師', ARRAY['Hair Stylist'], true),
  ('美甲師', ARRAY['Nail Technician'], true),
  ('家教', ARRAY['Tutor'], true),
  ('翻譯', ARRAY['Translator'], true),
  ('保母', ARRAY['Nanny','育兒'], true),
  ('會計', ARRAY['Accountant'], true),
  ('人資', ARRAY['HR','Human Resources'], true);
